[book]
title = "Digital Authorship"
# author = "N. S. Reiss"
authors = ["N. S. Reiss", "N. S. Reiss minime"]
description = "The example book covers examples."

src = "src"
language = "en"
multilingual = false
